import random
from pyrogram import filters
from AbhiXMusic import app


# List of 1210 advice in Hindi and English, with various categories
FALLBACK_ADVICE = [
    # Existing 210 Advice (Copied from Previous Version)
    # Motivational (English)
    "Keep pushing forward—you’re closer to your dreams than you think! 💪",
    "Every small step counts; don’t give up on your journey! 🚀",
    "Believe in yourself; you’re stronger than you realize! 🌟",
    "The best way to predict the future is to create it! ✨",
    "Challenges are just opportunities in disguise—face them head-on! 💥",
    "Your hard work will pay off; stay focused and keep going! 🏆",
    "Success is the sum of small efforts repeated daily! 📈",
    "Don’t wait for the perfect moment—make the moment perfect! ⏳",
    "You’ve got this! Trust your journey and keep moving forward! 🛤️",
    "Dream big, work hard, and never stop believing in yourself! 🌈",

    # Motivational (Hindi)
    "Aage badhte raho—tum apne sapnon se zyada kareeb ho! 💪",
    "Har chhota kadam maayne rakhta hai; haar mat maano! 🚀",
    "Apne aap par bharosa rakho; tum soch se zyada takatvar ho! 🌟",
    "Apna future banane ka behtareen tareeka hai usse abhi shuru kar do! ✨",
    "Chunautiyaan toh bas mauke hain—unka saamna karo! 💥",
    "Tumhari mehnat rang layegi; focus rakho aur aage badho! 🏆",
    "Chhote chhote efforts se badi kaamyabi milti hai! 📈",
    "Perfect waqt ka intezaar mat karo—waqt ko perfect bana do! ⏳",
    "Tum kar sakte ho! Apne safar par bharosa rakho aur aage badho! 🛤️",
    "Bade sapne dekho, mehnat karo, aur kabhi apne aap par shak mat karo! 🌈",

    # Funny (English)
    "Don’t worry, if Plan A fails, there are 25 more letters! 😂",
    "Life’s too short—eat the cake first! 🍰",
    "If at first you don’t succeed, order pizza! 🍕",
    "I put the ‘pro’ in procrastination—beat that! 😜",
    "Why fit in when you were born to stand out… or nap? 😴",
    "Be like Wi-Fi—connect with everyone, but don’t let everyone connect with you! 📶",
    "I’m not lazy, I’m just on energy-saving mode! ⚡",
    "If life gives you lemons, trade them for coffee. 🍋➡️☕",
    "Some people graduate with honors; I am just honored to graduate! 🎓",
    "I’m not clumsy; the floor just loves me too much! 🤕",

    # Funny (Hindi)
    "Chinta mat kar, agar Plan A fail ho gaya, toh 25 aur letters hain! 😂",
    "Zindagi chhoti hai—pehle cake kha lo! 🍰",
    "Pehli baar mein kaam na ho, toh pizza order kar lo! 🍕",
    "Main procrastination mein ‘pro’ hoon—isse beat kar ke dikhao! 😜",
    "Fit hone ka kya fayda jab tum standout ya so sakte ho? 😴",
    "Wi-Fi ki tarah bano—sabse connect karo, par sabko connect mat hone do! 📶",
    "Main aalsi nahi, bas energy-saving mode pe hoon! ⚡",
    "Agar zindagi ne nimboo diye, toh coffee se exchange kar lo! 🍋➡️☕",
    "Kuch log honors ke saath pass hote hain; main bas pass hone ke liye honored hoon! 🎓",
    "Main clumsy nahi hoon; zameen mujhe zyada pyar karti hai! 🤕",

    # Life Advice (English)
    "Surround yourself with people who lift you up! 🤗",
    "Take time to appreciate the little things in life. 🌸",
    "Don’t compare your journey to others—everyone’s path is unique! 🛤️",
    "Be kind to yourself; you’re doing the best you can. 💖",
    "Sometimes a small break can recharge you for the journey ahead! 🌴",
    "Focus on progress, not perfection—keep moving forward! 📈",
    "Learn from your mistakes; they’re your best teachers! 📚",
    "Stay curious—there’s always something new to learn! 🔍",
    "Don’t be afraid to ask for help; we all need support sometimes! 🤝",
    "Celebrate your wins, no matter how small—they matter! 🎉",

    # Life Advice (Hindi)
    "Aise logon ke saath raho jo tumhe aage badhayein! 🤗",
    "Zindagi ke chhote chhote palon ki kadar karo. 🌸",
    "Apne safar ki tulna doosron se mat karo—har kisi ka raasta alag hai! 🛤️",
    "Apne aap ke saath meharbaan raho; tum apna best kar rahe ho. 💖",
    "Kabhi kabhi chhota break tumhe aage ke safar ke liye recharge kar sakta hai! 🌴",
    "Perfection pe nahi, progress pe dhyan do—aage badhte raho! 📈",
    "Apni galtiyon se seekho; woh tumhare sabse bade guru hain! 📚",
    "Curious raho—hamesha kuch naya seekhne ko hota hai! 🔍",
    "Madad maangne se mat daro; hum sabko kabhi na kabhi support chahiye hota hai! 🤝",
    "Apni chhoti chhoti jeeton ko celebrate karo—woh maayne rakhti hain! 🎉",

    # Random/Witty (English)
    "Life’s a journey—pack snacks! 🍫",
    "Be a pineapple: stand tall, wear a crown, and be sweet on the inside! 🍍",
    "You’re not late; you’re just on ‘fashionably delayed’ time! ⏰",
    "If you can’t convince them, confuse them! 🤯",
    "Smile—it’s the second-best thing you can do with your lips! 😁",
    "Some days you’re the pigeon, some days the statue—just roll with it! 🐦",
    "Be the kind of person your dog thinks you are! 🐶",
    "When nothing goes right, go left! ⬅️",
    "You’re one in a melon—don’t forget that! 🍉",
    "Life’s too short to take seriously—so dance in the rain! ☔",

    # Random/Witty (Hindi)
    "Zindagi ek safar hai—snacks pack kar lo! 🍫",
    "Pineapple ki tarah bano: lambi khadi raho, crown pehno, aur andar se meethi raho! 🍍",
    "Tum late nahi ho; bas ‘fashionably delayed’ time pe ho! ⏰",
    "Agar unhe convince nahi kar sakte, toh confuse kar do! 🤯",
    "Muskurao—yeh tumhare honthon ke saath doosri best cheez hai! 😁",
    "Kabhi kabhi tum kabootar ho, kabhi moorti—bas chalte raho! 🐦",
    "Waisa insaan bano jo tumhara kutta samajhta hai! 🐶",
    "Jab kuch sahi na jaye, toh left jao! ⬅️",
    "Tum ek tarbooz mein ek ho—yeh mat bhoolo! 🍉",
    "Zindagi bohot chhoti hai serious lene ke liye—toh baarish mein naacho! ☔",

    # More Advice to Reach 200+ (Mix of All Categories)
    "Don’t overthink—just take a deep breath and go for it! 🌬️",
    "Tum zyada soch rahe ho—saans lo aur bas kar do! 🌬️",
    "The best revenge is living well—show them how it’s done! 😎",
    "Sabse bada badla hai achha jeena—dikhao kaise karte hain! 😎",
    "I’m on a seafood diet—I see food, and I eat it! 🍔",
    "Main seafood diet pe hoon—khaana dekha aur kha liya! 🍔",
    "Let go of what you can’t change; focus on what you can! 🌟",
    "Jo badal nahi sakte usse chhod do; jo badal sakte ho uspe dhyan do! 🌟",
    "You’re never too old to set a new goal—go for it! 🏁",
    "Naya goal set karne ke liye kabhi buddha nahi hote—karo! 🏁",
    "Life’s a game—play it like a pro! 🎮",
    "Zindagi ek khel hai—pro ki tarah khelo! 🎮",
    "I told my Wi-Fi to behave—it’s still not listening! 📶",
    "Maine apne Wi-Fi se kaha behave karo—abhi bhi nahi sunta! 📶",
    "Keep your friends close and your snacks closer! 🍟",
    "Doston ko kareeb rakho aur snacks ko aur kareeb! 🍟",
    "Sometimes silence is the best answer—try it! 🤫",
    "Kabhi kabhi chup rehna hi sabse bada jawab hai—try karo! 🤫",
    "You’re a limited edition—don’t let anyone tell you otherwise! 🌟",
    "Tum limited edition ho—kisi ko kuch aur kehne mat do! 🌟",
    "I’m not arguing, I’m just explaining why I’m right! 😏",
    "Main jhagda nahi kar raha, bas samjha raha hoon ki main sahi kyun hoon! 😏",
    "Stay hydrated—both with water and good vibes! 💧",
    "Paani aur achhe vibes dono se hydrated raho! 💧",
    "If you stumble, make it part of the dance! 💃",
    "Agar thokar lagi, toh usse dance ka hissa bana do! 💃",
    "Be the sunshine on a cloudy day! ☀️",
    "Badalon wale din mein suraj ki tarah chamko! ☀️",
    "I’m not short; I’m just concentrated awesome! 😎",
    "Main chhota nahi hoon; bas concentrated awesome hoon! 😎",
    "Don’t chase—build your own path and let them follow! 🛤️",
    "Peechhe mat bhago—apna raasta banao aur unhe follow karne do! 🛤️",
    "Life’s too short to match socks—go wild! 🧦",
    "Zindagi chhoti hai socks match karne ke liye—thodi wild ho jao! 🧦",
    "You’re a masterpiece in progress—keep creating! 🎨",
    "Tum ek masterpiece ho jo ban raha hai—banate raho! 🎨",
    "I’m not weird; I’m just a limited edition! 🤪",
    "Main ajeeb nahi hoon; bas limited edition hoon! 🤪",
    "Be the reason someone smiles today! 😊",
    "Aaj kisi ke muskurahat ki wajah bano! 😊",
    "If it doesn’t challenge you, it won’t change you! 💪",
    "Agar yeh tumhe challenge nahi karta, toh yeh tumhe badal bhi nahi sakta! 💪",
    "I’m on a roll—just not sure where I’m rolling to! 🌀",
    "Main roll pe hoon—bas yeh nahi pata kahan ja raha hoon! 🌀",
    "Keep your chin up—or you’ll trip over your own ego! 😜",
    "Apni thodi upar rakho—warna apne ego se thokar kha jaoge! 😜",
    "You’re the CEO of your own life—make bold decisions! 💼",
    "Tum apni zindagi ke CEO ho—bold decisions lo! 💼",
    "I’m not lost; I’m just exploring new routes! 🗺️",
    "Main khoya nahi hoon; bas naye raaste explore kar raha hoon! 🗺️",
    "Stay true to yourself—everyone else is taken! 😎",
    "Apne aap ke saath sachche raho—baaki sab toh already booked hain! 😎",
    "I’m not ignoring you; I’m just prioritizing my snacks! 🍫",
    "Main tumhe ignore nahi kar raha; bas apne snacks ko priority de raha hoon! 🍫",
    "Be a voice, not an echo—speak your truth! 🗣️",
    "Ek awaaz bano, goonj nahi—apna sach bolo! 🗣️",
    "I’m not a morning person; I’m a coffee person! ☕",
    "Main morning person nahi hoon; main coffee person hoon! ☕",
    "Keep growing—flowers don’t bloom overnight! 🌸",
    "Badhte raho—phool raat bhar mein nahi khilte! 🌸",
    "I’m not messy; I’m just creatively organized! 🖌️",
    "Main ganda nahi hoon; bas creatively organized hoon! 🖌️",
    "Be the spark that lights up someone’s day! 🔥",
    "Woh chamak bano jo kisi ke din ko roshan kar de! 🔥",
    "I’m not late; I’m just making a grand entrance! 🎭",
    "Main late nahi hoon; bas ek grand entry kar raha hoon! 🎭",
    "Stay humble, but let them know you’re awesome! 😎",
    "Narmi rakho, par unhe pata chale ki tum awesome ho! 😎",
    "I’m not overthinking; I’m just over-preparing! 🧠",
    "Main zyada nahi soch raha; bas zyada taiyaari kar raha hoon! 🧠",
    "Be the rainbow after someone’s storm! 🌈",
    "Kisi ke toofan ke baad rainbow bano! 🌈",
    "I’m not clumsy; I’m just dancing with gravity! 💃",
    "Main clumsy nahi hoon; bas gravity ke saath dance kar raha hoon! 💃",
    "Keep shining—your light inspires others! ✨",
    "Chamakate raho—tumhari roshni doosron ko inspire karti hai! ✨",

    # New 1000 Advice (Total: 1210)

    # Friendship (English) - 50
    "A true friend is like a star—you don’t see them all the time, but they’re always there! 🌟",
    "Make friends who make you laugh so hard that you forget your worries! 😂",
    "Good friends don’t let you do stupid things… alone! 😜",
    "Surround yourself with friends who feel like sunshine on a cloudy day! ☀️",
    "A friend who listens is worth more than gold—cherish them! 💖",
    "Friends are the family you choose—pick wisely! 👨‍👩‍👧‍👦",
    "Be the friend you’d want to have—loyal, fun, and always there! 🤝",
    "Sometimes a coffee date with a friend can fix everything! ☕",
    "True friends don’t judge—they laugh with you at your mistakes! 😅",
    "Life’s better with friends who share your weirdness! 🤪",
    "A friend’s hug can make any bad day better—spread the love! 🥰",
    "Don’t let distance break your friendship—real friends stay connected! 📱",
    "Celebrate your friends’ successes like they’re your own! 🎉",
    "A friend who brings snacks is a keeper—never let them go! 🍫",
    "Be the friend who shows up, even when it’s inconvenient! 🚗",
    "Friendship isn’t about perfection—it’s about being real! 💯",
    "A good friend knows all your stories; a best friend helped you write them! 📖",
    "Make time for your friends—they’re the spice of life! 🌶️",
    "Friends who vibe together, thrive together—find your tribe! 🎶",
    "Be a friend who inspires others to be their best selves! 🌈",
    "A friend’s advice can be a game-changer—listen closely! 🗣️",
    "Don’t take your friends for granted—tell them they matter! 💌",
    "Friends are like Wi-Fi—stay connected, even when the signal’s weak! 📶",
    "A true friend sticks around during your storms, not just your sunshine! ⛈️",
    "Laugh with your friends—it’s the best therapy! 😄",

    # Friendship (Hindi) - 50
    "Sachcha dost ek sitare jaisa hai—hamesha nahi dikhta, par hamesha saath hota hai! 🌟",
    "Aise dost banao jo tumhe itna hasayein ki tum apni pareshaniyan bhool jao! 😂",
    "Ache dost tumhe akela bewakoofi nahi karne dete—saath dete hain! 😜",
    "Aise doston ke saath raho jo badalon mein suraj ki tarah lagein! ☀️",
    "Ek dost jo sunta hai, woh sone se zyada keemti hai—uski kadar karo! 💖",
    "Dost woh parivaar hain jo tum chunte ho—dhyan se chuno! 👨‍👩‍👧‍👦",
    "Woh dost bano jo tumhe chahiye—wafadar, mazedaar, aur hamesha saath! 🤝",
    "Kabhi kabhi dost ke saath ek coffee date sab theek kar sakta hai! ☕",
    "Sachche dost judge nahi karte—woh tumhari galtiyon pe saath mein hanste hain! 😅",
    "Zindagi un doston ke saath behtar hai jo tumhari ajeebpanti share karte hain! 🤪",
    "Ek dost ka jhappi kisi bhi bure din ko behtar bana sakta hai—pyar baanto! 🥰",
    "Dooriyan apni dosti na tode—asli dost hamesha connected rehte hain! 📱",
    "Apne doston ki kaamyabi ko apni tarah celebrate karo! 🎉",
    "Jo dost snacks laaye, woh keeper hai—use kabhi mat jaane do! 🍫",
    "Woh dost bano jo mushkil waqt mein bhi saath de! 🚗",
    "Dosti perfection ke baare mein nahi—sachchai ke baare mein hai! 💯",
    "Acha dost tumhari saari kahaniyaan jaanta hai; best friend ne unhe likhne mein madad ki! 📖",
    "Apne doston ke liye waqt nikalo—woh zindagi ka masala hain! 🌶️",
    "Jo dost saath vibe karte hain, woh saath badhte hain—apni tribe dhoondho! 🎶",
    "Woh dost bano jo doosron ko unka best version banne ke liye inspire kare! 🌈",
    "Ek dost ki salah zindagi badal sakti hai—dhyaan se suno! 🗣️",
    "Apne doston ko granted mat lo—unhe batayo ki woh maayne rakhte hain! 💌",
    "Dost Wi-Fi ki tarah hote hain—signal kamzor ho toh bhi connected raho! 📶",
    "Sachcha dost toofan mein bhi saath deta hai, sirf dhoop mein nahi! ⛈️",
    "Apne doston ke saath haso—yeh sabse best therapy hai! 😄",

    # Love (English) - 50
    "Love is like a Wi-Fi signal—just when you think you’re connected, it drops! 💕",
    "Be with someone who makes your heart smile every day! 😊",
    "A small ‘I love you’ can make someone’s whole day—say it often! 💖",
    "Love isn’t perfect, but it’s worth every imperfect moment! 🌹",
    "Hold hands, not grudges—love grows when you let go! 🤝",
    "The best love is the one that makes you a better person! 🌟",
    "Love is in the little things—like a shared laugh or a warm hug! 🥰",
    "Be someone’s sunshine, even on their cloudiest days! ☀️",
    "Love is a journey—enjoy every step with your partner! 🛤️",
    "A true lover fights for you, not with you—cherish them! ⚔️",
    "Love means saying sorry, even when you’re right—keep the peace! ✌️",
    "Surprise your partner with small gestures—they mean the world! 🎁",
    "Love is like a song—find the rhythm that suits you both! 🎶",
    "Be each other’s safe place in a chaotic world! 🏰",
    "Love grows when you water it with kindness and patience! 🌱",
    "A loving heart sees beauty in the smallest things—look closer! 👀",
    "Dance together, even if there’s no music—love makes its own! 💃🕺",
    "Love is giving someone your time—it’s the most precious gift! ⏳",
    "Be the reason your partner believes in forever! 💍",
    "Love isn’t about finding the perfect person—it’s about loving perfectly! 💞",
    "A kiss can say more than words—don’t hold back! 😘",
    "Love is a team sport—play together, win together! 🏆",
    "Be the kind of partner you’d want to have—loving and supportive! 🤗",
    "Love means growing together, not growing apart—stay connected! 🌿",
    "Every love story is beautiful—make yours the best! 📖",

    # Love (Hindi) - 50
    "Pyar Wi-Fi signal jaisa hai—jab lagta hai connected ho, tab disconnect ho jata hai! 💕",
    "Uske saath raho jo har din tumhare dil ko muskuraye! 😊",
    "Ek chhota ‘I love you’ kisi ka pura din bana sakta hai—aksar kaho! 💖",
    "Pyar perfect nahi hota, par har imperfect pal ke liye worth hai! 🌹",
    "Haath pakdo, naaraazgi nahi—pyar tab badhta hai jab chhod do! 🤝",
    "Sabse acha pyar woh hai jo tumhe behtar insaan banaye! 🌟",
    "Pyar chhoti chhoti cheezon mein hai—jaise ek saath hansi ya garam jhappi! 🥰",
    "Kisi ke badalon wale din mein unki dhoop bano! ☀️",
    "Pyar ek safar hai—apne partner ke saath har kadam ka maza lo! 🛤️",
    "Sachcha pyar wala ladta hai tumhare liye, tumse nahi—uski kadar karo! ⚔️",
    "Pyar mein sorry kehna padta hai, chahe sahi ho—aman rakho! ✌️",
    "Apne partner ko chhoti chhoti cheezon se surprise karo—yeh bohot maayne rakhta hai! 🎁",
    "Pyar ek gaane jaisa hai—woh rhythm dhoondho jo dono ke liye perfect ho! 🎶",
    "Ek doosre ke liye safe place bano is chaotic duniya mein! 🏰",
    "Pyar tab badhta hai jab tum isse kindness aur patience se seenchte ho! 🌱",
    "Pyar wala dil chhoti cheezon mein sundarta dekhta hai—kareeb se dekho! 👀",
    "Saath mein naacho, chahe music na ho—pyar apna music banata hai! 💃🕺",
    "Pyar matlab kisi ko apna waqt dena—yeh sabse keemti tohfa hai! ⏳",
    "Woh bano jo apne partner ko forever pe yakeen dilaye! 💍",
    "Pyar perfect insaan dhoondhne ka nahi—perfect tareeke se pyar karne ka naam hai! 💞",
    "Ek kiss shabdon se zyada bol sakti hai—rokna mat! 😘",
    "Pyar ek team sport hai—saath khelo, saath jeeto! 🏆",
    "Woh partner bano jo tumhe chahiye—pyar aur support dene wala! 🤗",
    "Pyar matlab saath badhna, alag nahi hona—connected raho! 🌿",
    "Har pyar ki kahani sundar hoti hai—apni kahani best banao! 📖",

    # Self-Care (English) - 50
    "Take a deep breath—you’ve got this! 🌬️",
    "Put yourself first sometimes—it’s not selfish, it’s necessary! 💖",
    "A warm bath can fix almost anything—try it! 🛁",
    "Turn off your phone for an hour and just breathe! 📴",
    "You can’t pour from an empty cup—fill yourself with love! ☕",
    "Go for a walk and let nature heal your soul! 🌳",
    "Write down your worries, then let them go! 📝",
    "Treat yourself to your favorite snack—you deserve it! 🍫",
    "Sleep is your superpower—don’t skip it! 😴",
    "Dance like nobody’s watching—it’s good for your soul! 💃",
    "Say ‘no’ without guilt—you’re allowed to set boundaries! 🚫",
    "Listen to your favorite song and let it lift your mood! 🎶",
    "You’re enough, just as you are—believe it! 🌟",
    "Take a day to do nothing—it’s okay to rest! 🛋️",
    "Drink water, stretch, and smile—you’ll feel better! 💧",
    "Unplug and read a book—give your mind a break! 📚",
    "Celebrate your progress, not just your perfection! 🎉",
    "Surround yourself with positivity—it’s contagious! 🌈",
    "Meditate for 5 minutes—it can change your whole day! 🧘",
    "You’re a work in progress, and that’s beautiful! 🎨",
    "Laugh out loud—it’s the best medicine! 😂",
    "Do something that makes you happy every day! 😊",
    "Take care of your body—it’s your only home! 🏋️",
    "Be gentle with yourself—you’re doing great! 🤗",
    "Self-care isn’t a luxury, it’s a necessity—prioritize it! 🌿",

    # Self-Care (Hindi) - 50
    "Gehri saans lo—tum yeh kar sakte ho! 🌬️",
    "Kabhi kabhi apne aap ko pehle rakho—yeh selfish nahi, zaruri hai! 💖",
    "Ek garam nahaan sab theek kar sakta hai—try karo! 🛁",
    "Ek ghante ke liye phone band karo aur bas saans lo! 📴",
    "Khali cup se paani nahi daal sakte—apne aap ko pyar se bharo! ☕",
    "Walk pe jao aur nature ko apni rooh ko heal karne do! 🌳",
    "Apni pareshaniyan likho, phir chhod do! 📝",
    "Apna favorite snack khud ke liye lo—tum iske haqdaar ho! 🍫",
    "Neend tumhari superpower hai—ise skip mat karo! 😴",
    "Aise naacho jaise koi dekh nahi raha—yeh rooh ke liye acha hai! 💃",
    "Bina guilt ke ‘na’ kaho—tumhe boundaries set karne ka haq hai! 🚫",
    "Apna favorite gaana suno aur mood ko lift karo! 🎶",
    "Tum kaafi ho, jaise ho—yakeen karo! 🌟",
    "Ek din kuch mat karo—rest karna theek hai! 🛋️",
    "Paani piyo, stretch karo, aur muskurao—behtar feel karoge! 💧",
    "Unplug karo aur ek kitab padho—apne dimag ko break do! 📚",
    "Apni progress celebrate karo, perfection nahi! 🎉",
    "Positivity ke saath ghero—yeh chhota hai! 🌈",
    "5 minute ke liye meditate karo—yeh pura din badal sakta hai! 🧘",
    "Tum ek masterpiece ho jo ban raha hai—aur yeh sundar hai! 🎨",
    "Zor se haso—yeh sabse best dawa hai! 😂",
    "Har din woh karo jo tumhe khushi de! 😊",
    "Apne shareer ka khayal rakho—yeh tumhara ghar hai! 🏋️",
    "Apne aap ke saath narmi se pesh aao—tum bohot acha kar rahe ho! 🤗",
    "Self-care luxury nahi, zarurat hai—ise priority do! 🌿",

    # More Motivational (English) - 50
    "Rise above the storm—you’ll find the sunshine! ☀️",
    "Your only limit is your mind—break free! 🧠",
    "Turn your obstacles into stepping stones! 🪨",
    "Keep going—every step takes you closer to your goal! 🏁",
    "You’re unstoppable when you believe in yourself! 🚀",
    "The harder you work, the luckier you get! 🍀",
    "Don’t stop until you’re proud of yourself! 🏆",
    "Your dreams are waiting—go chase them! 🌟",
    "Be fearless in the pursuit of what sets your soul on fire! 🔥",
    "You’re stronger than your excuses—push forward! 💪",
    "Success doesn’t come to you—you go to it! 🛤️",
    "Every day is a fresh start—make it count! 🌅",
    "Your potential is endless—tap into it! 🌌",
    "Don’t fear failure—it’s just a lesson in disguise! 📚",
    "You’re a warrior—fight for your dreams! ⚔️",
    "The best views come after the hardest climbs! 🏔️",
    "Stay committed—great things take time! ⏳",
    "You’re a diamond in the making—keep shining! 💎",
    "Your journey is yours—own it with pride! 🛣️",
    "Keep climbing—the top is worth the effort! 🧗",
    "Don’t let fear stop you—let it fuel you! 🔥",
    "You’re a game-changer—play to win! 🎮",
    "The only way to fail is to stop trying! 🚫",
    "Your passion is your power—unleash it! ⚡",
    "Be the hero of your own story—write a great ending! 📖",

    # More Motivational (Hindi) - 50
    "Toofan ke upar utho—tumhe dhoop milegi! ☀️",
    "Tumhari sirf had tumhara dimag hai—uske paar jao! 🧠",
    "Apni rukavaton ko seedhi bana do! 🪨",
    "Chalte raho—har kadam tumhe apne goal ke kareeb le jata hai! 🏁",
    "Tum ruk nahi sakte jab tum apne aap par yakeen karte ho! 🚀",
    "Jitna zyada mehnat karoge, utne lucky banoge! 🍀",
    "Tab tak mat ruko jab tak tum khud pe proud na ho! 🏆",
    "Tumhare sapne intezaar kar rahe hain—unke peechhe bhaago! 🌟",
    "Us cheez ke liye be-darr bano jo tumhari rooh mein aag lagaye! 🔥",
    "Tum apne excuses se zyada takatvar ho—aage badho! 💪",
    "Kaamyabi tumhare paas nahi aati—tumhe uske paas jana padta hai! 🛤️",
    "Har din ek nayi shuruaat hai—ise maayne do! 🌅",
    "Tumhari capability anant hai—isse tap karo! 🌌",
    "Haar se mat daro—yeh toh bas ek seekh hai chhupi hui! 📚",
    "Tum ek yoddha ho—apne sapnon ke liye lado! ⚔️",
    "Sabse sundar nazare sabse mushkil chadhai ke baad aate hain! 🏔️",
    "Committed raho—badi cheezein waqt leti hain! ⏳",
    "Tum ek heera ho ban raha hai—chamakate raho! 💎",
    "Tumhara safar tumhara hai—ise fakr se apnao! 🛣️",
    "Chadhate raho—upar ka nazara mehnat ke layak hai! 🧗",
    "Darr ko tumhe rokne mat do—usse apni taakat banao! 🔥",
    "Tum game-changer ho—jeetne ke liye khelo! 🎮",
    "Haar ka sirf ek tareeka hai—koshish chhod dena! 🚫",
    "Tumhara passion tumhari taakat hai—ise chhod do! ⚡",
    "Apni kahani ka hero bano—ek zabardast ending likho! 📖",

    # More Funny (English) - 50
    "I’m on a diet—I only eat food that makes me happy! 🍔",
    "I don’t trip; I do random gravity checks! 🤸",
    "My bed and I are in a committed relationship—sorry, alarm clock! ⏰",
    "I’m not a morning person, but I’m a breakfast person! 🥐",
    "I told my boss I’m working from home—my bed counts, right? 🛏️",
    "I’m not late; I’m just practicing for the slow-motion scene! 🎬",
    "My wallet is like an onion—opening it makes me cry! 😢",
    "I don’t snore; I dream I’m a motorcycle! 🏍️",
    "I’m not forgetting things; I’m just practicing for old age! 👴",
    "I don’t need a hairstylist—my pillow does a great job! 💇",
    "I’m not avoiding work; I’m just on a creative break! 🎨",
    "I don’t have a bad day—I have a ‘character-building’ day! 🏋️",
    "I’m not clumsy; I’m just testing the durability of everything! 🔨",
    "I don’t diet; I just eat in slow motion! 🐢",
    "I’m not ignoring you; I’m just practicing selective hearing! 👂",
    "I don’t get lost; I take the scenic route! 🗺️",
    "I’m not a procrastinator; I’m a professional deadline tester! ⏳",
    "I don’t have a messy room; I have a treasure hunt setup! 🏴‍☠️",
    "I’m not sleeping; I’m just charging my awesomeness! ⚡",
    "I don’t make mistakes; I create learning opportunities! 📚",
    "I’m not broke; I’m just pre-rich! 💰",
    "I don’t overeat; I just love food too much! 🍕",
    "I’m not single; I’m just in a long-term relationship with freedom! 🕊️",
    "I don’t sweat; I sparkle under pressure! ✨",
    "I’m not addicted to coffee; we’re just in a serious relationship! ☕",

    # More Funny (Hindi) - 50
    "Main diet pe hoon—sirf wahi khaata hoon jo mujhe khushi de! 🍔",
    "Main thokar nahi khaata; bas random gravity checks karta hoon! 🤸",
    "Mera bed aur main committed relationship mein hain—sorry, alarm clock! ⏰",
    "Main morning person nahi hoon, lekin breakfast person hoon! 🥐",
    "Maine boss se kaha main ghar se kaam kar raha hoon—mera bed count hota hai na? 🛏️",
    "Main late nahi hoon; bas slow-motion scene ki practice kar raha hoon! 🎬",
    "Mera wallet ek pyaaz jaisa hai—kholo toh rula deta hai! 😢",
    "Main kharrate nahi marta; main sapne mein motorcycle hoon! 🏍️",
    "Main cheezein nahi bhoolta; bas budhapa ki practice kar raha hoon! 👴",
    "Mujhe hairstylist ki zarurat nahi—mera takiya acha kaam karta hai! 💇",
    "Main kaam se bhaag nahi raha; bas creative break pe hoon! 🎨",
    "Mera din kharab nahi hota—bas ‘character-building’ din hota hai! 🏋️",
    "Main clumsy nahi hoon; bas har cheez ki durability test kar raha hoon! 🔨",
    "Main diet nahi karta; bas slow motion mein khaata hoon! 🐢",
    "Main tumhe ignore nahi kar raha; bas selective hearing ki practice kar raha hoon! 👂",
    "Main khoya nahi hoon; bas scenic route le raha hoon! 🗺️",
    "Main procrastinator nahi hoon; main professional deadline tester hoon! ⏳",
    "Mera kamra ganda nahi hai; maine treasure hunt setup kiya hai! 🏴‍☠️",
    "Main so nahi raha; bas apni awesomeness charge kar raha hoon! ⚡",
    "Main galtiyan nahi karta; main seekhne ke mauke banata hoon! 📚",
    "Main toota nahi hoon; bas pre-rich hoon! 💰",
    "Main zyada nahi khaata; bas khane se zyada pyar karta hoon! 🍕",
    "Main single nahi hoon; bas freedom ke saath long-term relationship mein hoon! 🕊️",
    "Main pasina nahi bahata; main pressure mein chamakta hoon! ✨",
    "Main coffee ka addict nahi hoon; hum bas serious relationship mein hain! ☕",

    # More Life Advice (English) - 50
    "Don’t rush—good things take time to grow! 🌱",
    "Forgive others, not because they deserve it, but because you deserve peace! ✌️",
    "Your past doesn’t define you—your choices do! 🛤️",
    "Be patient with yourself—you’re a work in progress! 🎨",
    "Sometimes the best thing you can do is let go! 🍃",
    "Stay grounded, but let your dreams soar! 🕊️",
    "The best way to find yourself is to lose yourself in helping others! 🤝",
    "Don’t fear change—it’s the only way to grow! 🌟",
    "Be grateful for what you have—it’s the key to happiness! 🙏",
    "Life’s a puzzle—keep finding the pieces that fit! 🧩",
    "Stay kind, even when the world isn’t—your light matters! 💡",
    "Take risks—they lead to the best adventures! 🌍",
    "Don’t let negativity dim your shine—keep glowing! ✨",
    "Life’s too short to hold grudges—let them go! 🚫",
    "Be present—the moment you’re in is all you have! ⏳",
    "Surround yourself with those who see your worth! 💎",
    "You can’t control everything—focus on what you can! 🎯",
    "Life’s a journey, not a race—enjoy the ride! 🚗",
    "Be the change you wish to see in the world! 🌍",
    "Every challenge is a chance to grow stronger! 💪",
    "Don’t wait for opportunities—create them! 🔨",
    "Stay true to your values—they’re your compass! 🧭",
    "Life’s better when you share it with others—connect! 👥",
    "Keep learning—knowledge is your greatest asset! 📚",
    "You’re never stuck—you just need a new perspective! 🔄",

    # More Life Advice (Hindi) - 50
    "Jaldi mat karo—achhi cheezein badhne mein waqt leti hain! 🌱",
    "Doosron ko maaf karo, isliye nahi ki woh iske layak hain, balki tumhe sukoon chahiye! ✌️",
    "Tumhara past tumhe define nahi karta—tumhare faisle karte hain! 🛤️",
    "Apne aap ke saath sabr rakho—tum ban rahe ho! 🎨",
    "Kabhi kabhi sabse behtar kaam chhod dena hai! 🍃",
    "Zameen se juda raho, par sapnon ko udne do! 🕊️",
    "Apne aap ko dhoondhne ka behtareen tareeka hai doosron ki madad mein khud ko khona! 🤝",
    "Badlaav se mat daro—yeh badhne ka ek hi tareeka hai! 🌟",
    "Jo tumhare paas hai uske liye shukrguzaar raho—yeh khushi ki kunji hai! 🙏",
    "Zindagi ek puzzle hai—woh pieces dhoondhte raho jo fit ho! 🧩",
    "Meharbaan raho, chahe duniya na ho—tumhari roshni maayne rakhti hai! 💡",
    "Risk lo—woh behtareen adventures ki taraf le jaate hain! 🌍",
    "Negativity ko apni chamak kam na karne do—chamakate raho! ✨",
    "Zindagi chhoti hai naaraazgi rakhne ke liye—chhod do! 🚫",
    "Maujood raho—yeh pal hi tumhara hai! ⏳",
    "Un logon ke saath raho jo tumhari keemat samajhte hain! 💎",
    "Tum sab kuch control nahi kar sakte—jo kar sakte ho uspe focus karo! 🎯",
    "Zindagi ek safar hai, race nahi—maze lo! 🚗",
    "Woh badlaav bano jo duniya mein dekhna chahte ho! 🌍",
    "Har chunauti ek mauka hai mazboot hone ka! 💪",
    "Maukon ka intezaar mat karo—unhe banao! 🔨",
    "Apne values ke saath sachche raho—woh tumhara compass hain! 🧭",
    "Zindagi doosron ke saath baantne se behtar hoti hai—connect karo! 👥",
    "Seekhte raho—gyaan tumhari sabse badi daulat hai! 📚",
    "Tum kabhi phanse nahi ho—bas ek naye nazariye ki zarurat hai! 🔄",

    # More Random/Witty (English) - 50
    "I’m not a chef, but I can microwave like a pro! 🍲",
    "Life’s too short to fold fitted sheets—embrace the chaos! 🛏️",
    "I’m not a superhero, but I can nap like one! 😴",
    "My plants are the only ones thriving in this house! 🌱",
    "I’m not running away; I’m just jogging in the opposite direction! 🏃",
    "I don’t need a vacation—I need a new life! 🏝️",
    "I’m not a people person, but I’m a dog person! 🐶",
    "My to-do list and I are in a toxic relationship! 📋",
    "I’m not a morning person—I’m a ‘five more minutes’ person! ⏰",
    "I don’t chase dreams; I nap until they come to me! 💤",
    "I’m not ignoring you; I’m just on airplane mode! ✈️",
    "I don’t have bad days; I have plot twists! 📖",
    "I’m not a perfectionist; I’m a ‘good enough’ artist! 🎨",
    "I don’t follow trends; I set my own chaos! 🔥",
    "I’m not a night owl; I’m a midnight snack enthusiast! 🌙",
    "I don’t need a gym—I lift snacks to my mouth! 🍟",
    "I’m not a drama queen; I’m a drama emperor! 👑",
    "I don’t have a plan; I have a vibe! 🌈",
    "I’m not lost; I’m just taking the long way home! 🛤️",
    "I don’t need a therapist—I have my playlist! 🎶",
    "I’m not a rebel; I’m just creatively disobedient! 😈",
    "I don’t need a map—I’ll figure it out… eventually! 🗺️",
    "I’m not a hoarder; I’m a collector of memories! 📦",
    "I don’t need motivation—I need coffee! ☕",
    "I’m not extra; I’m just the deluxe version! ✨",

    # More Random/Witty (Hindi) - 50
    "Main chef nahi hoon, lekin microwave mein pro hoon! 🍲",
    "Zindagi chhoti hai fitted sheets fold karne ke liye—chaos ko apnao! 🛏️",
    "Main superhero nahi hoon, lekin so sakta hoon jaise ek! 😴",
    "Mere paudhe hi is ghar mein thrive kar rahe hain! 🌱",
    "Main bhaag nahi raha; bas opposite direction mein jog kar raha hoon! 🏃",
    "Mujhe vacation nahi chahiye—mujhe nayi zindagi chahiye! 🏝️",
    "Main logon ka dost nahi hoon, lekin kutton ka dost hoon! 🐶",
    "Meri to-do list aur main toxic relationship mein hain! 📋",
    "Main morning person nahi hoon—main ‘five more minutes’ person hoon! ⏰",
    "Main sapnon ke peechhe nahi bhaagta; main sota hoon jab tak woh aaye! 💤",
    "Main tumhe ignore nahi kar raha; bas airplane mode pe hoon! ✈️",
    "Mere din kharab nahi hote; mere plot twists hote hain! 📖",
    "Main perfectionist nahi hoon; main ‘good enough’ artist hoon! 🎨",
    "Main trends follow nahi karta; main apna chaos set karta hoon! 🔥",
    "Main night owl nahi hoon; main midnight snack enthusiast hoon! 🌙",
    "Mujhe gym ki zarurat nahi—main snacks apne muh tak uthata hoon! 🍟",
    "Main drama queen nahi hoon; main drama emperor hoon! 👑",
    "Mera koi plan nahi hai; mera ek vibe hai! 🌈",
    "Main khoya nahi hoon; bas ghar ka lamba raasta le raha hoon! 🛤️",
    "Mujhe therapist ki zarurat nahi—meri playlist hai! 🎶",
    "Main rebel nahi hoon; main bas creatively disobedient hoon! 😈",
    "Mujhe map ki zarurat nahi—main eventually samajh lunga! 🗺️",
    "Main hoarder nahi hoon; main yaadon ka collector hoon! 📦",
    "Mujhe motivation nahi chahiye—mujhe coffee chahiye! ☕",
    "Main extra nahi hoon; main bas deluxe version hoon! ✨",

    # Mixed Categories (English) - 250
    "You’re a star—don’t let anyone dim your light! 🌟",
    "I’m not a chef, but I can burn water like a pro! 🔥",
    "Life’s too short to be serious—laugh it off! 😂",
    "Be the reason someone believes in magic! 🪄",
    "I’m not lazy; I’m just practicing for hibernation! 🐻",
    "Stay curious—life’s an adventure waiting to unfold! 🌍",
    "I told my mirror I’m beautiful—it didn’t argue! 🪞",
    "You’re a masterpiece—don’t let anyone paint over you! 🎨",
    "I’m not a morning person—I’m a sunrise avoider! 🌅",
    "Keep your dreams big and your worries small! 🌈",
    "I don’t trip; I do a freestyle dance move! 💃",
    "Be a fountain of positivity in a desert of negativity! 💧",
    "I’m not lost; I’m just on a side quest! 🎮",
    "You’re the author of your story—write a bestseller! 📖",
    "I’m not clumsy; I’m just gravity’s best friend! 🤕",
    "Stay kind—it’s the best superpower you can have! 🦸",
    "I don’t need a vacation; I need a nap! 😴",
    "You’re a firework—light up the sky! 🎆",
    "I’m not ignoring you; I’m just on a mental vacation! 🏝️",
    "Be the kind of person who leaves a trail of glitter! ✨",
    "I’m not a procrastinator; I’m a strategic delayer! ⏳",
    "You’re a warrior—don’t let anyone steal your sword! ⚔️",
    "I don’t have bad days; I have comedic plot twists! 🎭",
    "Stay true to yourself—you’re a limited edition! 💎",
    "I’m not a people pleaser; I’m a pizza pleaser! 🍕",
    "You’re a garden—keep blooming, no matter the season! 🌸",
    "I’m not a night owl; I’m a star-gazing enthusiast! 🌠",
    "Be the kind of friend who makes life a party! 🎉",
    "I don’t overthink; I just think in 4D! 🧠",
    "You’re a melody—play your own tune! 🎵",
    "I’m not a rebel; I’m just a rule-bending artist! 🎨",
    "Stay hopeful—better days are always ahead! 🌞",
    "I’m not broke; I’m just on a budget adventure! 💸",
    "You’re a lighthouse—shine bright for others! 🏮",
    "I’m not a mess; I’m a work of abstract art! 🖼️",
    "Be the kind of person who makes Mondays exciting! 📅",
    "I don’t need a gym; I chase my dreams for cardio! 🏃",
    "You’re a treasure—don’t let anyone bury you! 🏴‍☠️",
    "I’m not a drama queen; I’m a drama festival! 🎭",
    "Stay adventurous—life’s too short to stay still! 🌍",
    "I’m not a morning person; I’m a coffee convert! ☕",
    "You’re a comet—leave a trail of magic! ☄️",
    "I’m not a perfectionist; I’m a ‘close enough’ expert! 🎯",
    "Be the kind of person who makes everyone feel seen! 👀",
    "I don’t need a plan; I have a playlist! 🎶",
    "You’re a phoenix—rise from the ashes! 🔥",
    "I’m not a hoarder; I’m a memory curator! 📦",
    "Stay vibrant—life’s too dull without your colors! 🎨",
    "I’m not a chef; I’m a snack enthusiast! 🍟",
    "You’re a spark—ignite something amazing! ⚡",
    # Adding more to reach 250 (200 more)
    "I’m not late; I’m just fashionably delayed! ⏰",
    "You’re a dreamer—don’t let reality stop you! 🌌",
    "I’m not a procrastinator; I’m a deadline thrill-seeker! ⏳",
    "Be the kind of person who makes every day count! 📆",
    "I don’t trip; I do a gravity audition! 🤸",
    "You’re a storm—make waves wherever you go! 🌊",
    "I’m not a morning person; I’m a brunch enthusiast! 🥞",
    "Stay bold—timidity doesn’t suit you! 😎",
    "I’m not ignoring you; I’m just on a vibe check! 🌈",
    "You’re a gem—don’t let anyone dull your sparkle! 💎",
    "I’m not a mess; I’m a chaos coordinator! 🌀",
    "Be the kind of person who makes life an adventure! 🌍",
    "I don’t need a gym; I lift my spirits daily! 🏋️",
    "You’re a starfish—regrow and shine brighter! 🌟",
    "I’m not a drama queen; I’m a drama galaxy! 🌌",
    "Stay curious—life’s a mystery worth solving! 🔍",
    "I’m not a night owl; I’m a moonlight dancer! 🌙",
    "You’re a balloon—rise above the noise! 🎈",
    "I’m not a perfectionist; I’m a ‘good vibes only’ expert! 🌈",
    "Be the kind of person who makes every moment magical! 🪄",
    "I don’t need a map; I’m a wandering soul! 🗺️",
    "You’re a wildfire—burn bright and fierce! 🔥",
    "I’m not a hoarder; I’m a collector of chaos! 📦",
    "Stay vibrant—life needs your energy! ⚡",
    "I’m not a chef; I’m a microwave magician! 🍲",
    "You’re a rainbow—color the world with your light! 🌈",
    "I’m not a morning person; I’m a sunset chaser! 🌅",
    "Be the kind of person who makes everyone smile! 😊",
    "I don’t overthink; I just think in surround sound! 🎧",
    "You’re a melody—play loud and proud! 🎵",
    "I’m not a rebel; I’m a rule-rewriting genius! ✍️",
    "Stay hopeful—sunshine always follows the rain! ☀️",
    "I’m not broke; I’m just on a financial adventure! 💸",
    "You’re a lighthouse—guide others with your light! 🏮",
    "I’m not a mess; I’m a chaotic masterpiece! 🖼️",
    "Be the kind of person who makes Mondays fun! 📅",
    "I don’t need a gym; I chase my goals for exercise! 🏃",
    "You’re a treasure—don’t let anyone hide you! 🏴‍☠️",
    "I’m not a drama queen; I’m a drama universe! 🌌",
    "Stay adventurous—life’s too short to play it safe! 🌍",
    "I’m not a morning person; I’m a coffee disciple! ☕",
    "You’re a comet—leave a trail of wonder! ☄️",
    "I’m not a perfectionist; I’m a ‘close enough’ champion! 🎯",
    "Be the kind of person who makes everyone feel loved! 💖",
    "I don’t need a plan; I have a vibe! 🌈",
    "You’re a phoenix—rise stronger every time! 🔥",
    "I’m not a hoarder; I’m a memory keeper! 📦",
    "Stay vibrant—life’s too gray without you! 🎨",
    "I’m not a chef; I’m a snack connoisseur! 🍟",
    "You’re a spark—start something extraordinary! ⚡",
    "I’m not late; I’m just on dramatic timing! ⏰",
    "You’re a dreamer—don’t let anyone wake you up! 🌌",
    "I’m not a procrastinator; I’m a deadline daredevil! ⏳",
    "Be the kind of person who makes every day special! 📆",
    "I don’t trip; I do a gravity performance! 🤸",
    "You’re a storm—shake things up! 🌊",
    "I’m not a morning person; I’m a brunch lover! 🥞",
    "Stay bold—life’s too short to play small! 😎",
    "I’m not ignoring you; I’m just on a vibe mission! 🌈",
    "You’re a gem—don’t let anyone dim your shine! 💎",
    "I’m not a mess; I’m a chaos maestro! 🌀",
    "Be the kind of person who makes life a thrill! 🌍",
    "I don’t need a gym; I lift my mood daily! 🏋️",
    "You’re a starfish—regenerate and glow! 🌟",
    "I’m not a drama queen; I’m a drama cosmos! 🌌",
    "Stay curious—life’s a puzzle worth solving! 🔍",
    "I’m not a night owl; I’m a moonlight poet! 🌙",
    "You’re a balloon—float above the drama! 🎈",
    "I’m not a perfectionist; I’m a ‘good vibes’ guru! 🌈",
    "Be the kind of person who makes every moment sparkle! 🪄",
    "I don’t need a map; I’m a wandering spirit! 🗺️",
    "You’re a wildfire—blaze your own trail! 🔥",
    "I’m not a hoarder; I’m a collector of dreams! 📦",
    "Stay vibrant—life needs your spark! ⚡",
    "I’m not a chef; I’m a microwave master! 🍲",
    "You’re a rainbow—paint the world with joy! 🌈",
    "I’m not a morning person; I’m a sunset dreamer! 🌅",
    "Be the kind of person who makes everyone laugh! 😊",
    "I don’t overthink; I just think in technicolor! 🎧",
    "You’re a melody—sing your own song! 🎵",
    "I’m not a rebel; I’m a rule-redefining visionary! ✍️",
    "Stay hopeful—better days are coming! ☀️",
    "I’m not broke; I’m just on a budget journey! 💸",
    "You’re a lighthouse—shine for those lost at sea! 🏮",
    "I’m not a mess; I’m a chaotic work of art! 🖼️",
    "Be the kind of person who makes Mondays amazing! 📅",
    "I don’t need a gym; I chase happiness for cardio! 🏃",
    "You’re a treasure—don’t let anyone bury your shine! 🏴‍☠️",
    "I’m not a drama queen; I’m a drama galaxy! 🌌",
    "Stay adventurous—life’s too short to be boring! 🌍",
    "I’m not a morning person; I’m a coffee devotee! ☕",
    "You’re a comet—leave a trail of awe! ☄️",
    "I’m not a perfectionist; I’m a ‘close enough’ master! 🎯",
    "Be the kind of person who makes everyone feel special! 💖",
    "I don’t need a plan; I have a rhythm! 🌈",
    "You’re a phoenix—rise with grace! 🔥",
    "I’m not a hoarder; I’m a memory archivist! 📦",
    "Stay vibrant—life’s too dull without your light! 🎨",
    "I’m not a chef; I’m a snack savant! 🍟",
    "You’re a spark—ignite the extraordinary! ⚡",
    "I’m not late; I’m just on epic timing! ⏰",
    "You’re a dreamer—don’t let anyone clip your wings! 🌌",
    "I’m not a procrastinator; I’m a deadline adventurer! ⏳",
    "Be the kind of person who makes every day a masterpiece! 📆",
    "I don’t trip; I do a gravity showcase! 🤸",
    "You’re a storm—make waves that inspire! 🌊",
    "I’m not a morning person; I’m a brunch aficionado! 🥞",
    "Stay bold—life’s too short to be timid! 😎",
    "I’m not ignoring you; I’m just on a vibe quest! 🌈",
    "You’re a gem—don’t let anyone dull your glow! 💎",
    "I’m not a mess; I’m a chaos conductor! 🌀",
    "Be the kind of person who makes life a joyride! 🌍",
    "I don’t need a gym; I lift my spirits for exercise! 🏋️",
    "You’re a starfish—regenerate and dazzle! 🌟",
    "I’m not a drama queen; I’m a drama universe! 🌌",
    "Stay curious—life’s a mystery worth exploring! 🔍",
    "I’m not a night owl; I’m a moonlight artist! 🌙",
    "You’re a balloon—rise above the chaos! 🎈",
    "I’m not a perfectionist; I’m a ‘good vibes’ master! 🌈",
    "Be the kind of person who makes every moment shine! 🪄",
    "I don’t need a map; I’m a wandering dreamer! 🗺️",
    "You’re a wildfire—burn with passion! 🔥",
    "I’m not a hoarder; I’m a collector of joy! 📦",
    "Stay vibrant—life needs your brilliance! ⚡",
    "I’m not a chef; I’m a microwave maestro! 🍲",
    "You’re a rainbow—color the world with happiness! 🌈",
    "I’m not a morning person; I’m a sunset enthusiast! 🌅",
    "Be the kind of person who makes everyone feel alive! 😊",
    "I don’t overthink; I just think in high definition! 🎧",
    "You’re a melody—play your own symphony! 🎵",
    "I’m not a rebel; I’m a rule-rewriting legend! ✍️",
    "Stay hopeful—sunshine always follows the storm! ☀️",
    "I’m not broke; I’m just on a financial quest! 💸",
    "You’re a lighthouse—guide others with your glow! 🏮",
    "I’m not a mess; I’m a chaotic genius! 🖼️",
    "Be the kind of person who makes Mondays legendary! 📅",
    "I don’t need a gym; I chase joy for cardio! 🏃",
    "You’re a treasure—don’t let anyone hide your light! 🏴‍☠️",
    "I’m not a drama queen; I’m a drama cosmos! 🌌",
    "Stay adventurous—life’s too short to be ordinary! 🌍",
    "I’m not a morning person; I’m a coffee worshipper! ☕",
    "You’re a comet—leave a trail of inspiration! ☄️",
    "I’m not a perfectionist; I’m a ‘close enough’ legend! 🎯",
    "Be the kind of person who makes everyone feel cherished! 💖",
    "I don’t need a plan; I have a beat! 🌈",
    "You’re a phoenix—rise with power! 🔥",
    "I’m not a hoarder; I’m a memory collector! 📦",
    "Stay vibrant—life’s too gray without your shine! 🎨",
    "I’m not a chef; I’m a snack expert! 🍟",
    "You’re a spark—ignite something incredible! ⚡",

    # Mixed Categories (Hindi) - 250
    "Tum ek sitara ho—kisi ko apni roshni kam mat karne do! 🌟",
    "Main chef nahi hoon, lekin paani jala sakta hoon jaise pro! 🔥",
    "Zindagi bohot chhoti hai serious hone ke liye—has ke chhod do! 😂",
    "Woh bano jo kisi ko jadoo pe yakeen dilaye! 🪄",
    "Main aalsi nahi hoon; bas hibernation ki practice kar raha hoon! 🐻",
    "Curious raho—zindagi ek adventure hai jo khulne ka intezaar kar rahi hai! 🌍",
    "Maine apne mirror se kaha main sundar hoon—usne jhagda nahi kiya! 🪞",
    "Tum ek masterpiece ho—kisi ko apne upar paint mat karne do! 🎨",
    "Main morning person nahi hoon—main sunrise avoider hoon! 🌅",
    "Apne sapne bade rakho aur pareshaniyan chhoti! 🌈",
    "Main thokar nahi khaata; bas freestyle dance move karta hoon! 💃",
    "Negativity ke registan mein positivity ka fountain bano! 💧",
    "Main khoya nahi hoon; bas ek side quest pe hoon! 🎮",
    "Tum apni kahani ke lekhak ho—bestseller likho! 📖",
    "Main clumsy nahi hoon; bas gravity ka best friend hoon! 🤕",
    "Meharbaan raho—yeh sabse bada superpower hai jo tumhare paas ho sakta hai! 🦸",
    "Mujhe vacation nahi chahiye; mujhe neend chahiye! 😴",
    "Tum ek firework ho—aasmaan ko roshan karo! 🎆",
    "Main tumhe ignore nahi kar raha; bas mental vacation pe hoon! 🏝️",
    "Woh insaan bano jo glitter ka trail chhod jaye! ✨",
    "Main procrastinator nahi hoon; main strategic delayer hoon! ⏳",
    "Tum ek yoddha ho—kisi ko apni talwaar churane mat do! ⚔️",
    "Mere din kharab nahi hote; mere comedic plot twists hote hain! 🎭"
    "Apne aap ke saath sachche raho—tum ek limited edition ho! 💎"
    "Main logon ko khush karne wala nahi hoon; main pizza khush karne wala hoon! 🍕",
    "Tum ek bagicha ho—har mausam mein khilte raho! 🌸"
    "Main night owl nahi hoon; main sitare dekhne wala hoon! 🌠"
    "Woh dost bano jo zindagi ko party banata hai! 🎉"
    "Main overthink nahi karta; main 4D mein sochta hoon! 🧠"
    "Tum ek melody ho—apna hi tune bajao! 🎵"
    "Main rebel nahi hoon; main bas rule-bending artist hoon! 🎨"
    "Umeed rakho—behtar din hamesha aate hain! 🌞"
    "Main toota nahi hoon; main bas budget adventure pe hoon! 💸"
    "Tum ek lighthouse ho—doosron ko apni roshni se raasta dikhao! 🏮"
    "Main mess nahi hoon; main abstract art ka kaam hoon! 🖼️"
    "Woh insaan bano jo Mondays ko exciting banata hai! 📅"
    "Mujhe gym ki zarurat nahi; main apne sapnon ka peecha karta hoon! 🏃"
    "Tum ek khazana ho—kisi ko tumhe chhupane mat do! 🏴‍☠️"
    "Main drama queen nahi hoon; main drama festival hoon! 🎭"
    "Stay adventurous—zindagi bohot chhoti hai safe khelne ke liye! 🌍"
    "Main morning person nahi hoon; main coffee convert hoon! ☕",
    "Tum ek comet ho—jadoo ka trail chhod do! ☄️",
    "Main perfectionist nahi hoon; main ‘close enough’ expert hoon! 🎯",
    "Woh insaan bano jo sabko dekhe—tumhari keemat maayne rakhti hai! 👀",
    "Mujhe plan ki zarurat nahi; meri playlist hai! 🎶",]

@app.on_message(filters.command("advice"))
async def advice(_, message):
    A = await message.reply_text("Fetching advice for you... ✨")
    # Pick a random advice from the local list
    advice_text = random.choice(FALLBACK_ADVICE)
    await A.edit(f"💡 **Advice for you**: {advice_text}")


__MODULE__ = "Aᴅᴠɪᴄᴇ"
__HELP__ = """
/advice - Gᴇᴛ ʀᴀɴᴅᴏᴍ ᴀᴅᴠɪᴄᴇ"""
